version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn src.wsgi -b 0.0.0.0:80"
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "80"
    

  db:
    image: postgres:latest
    container_name: ps01
    ports:
      - "5439:5432"
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      

volumes:
  postgres_data:
